[Greeter]
background=/usr/share/backgrounds/i3-setup-wallpaper.jpg
background-color=#2e3d44
draw-grid=false
theme-name=Pop-dark
icon-theme-name=Numix-Circle
font-name='Noto Sans 11'
xft-antialias=true
xft-hintstyle=hintfull
enable-hidpi=auto
